stages:
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: status_maxatslega_github_profile
      pushRemote: true
      registry: pcr.atslega.network
timeout: 60
notification: {}
