version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: status_maxatslega_github_profile
    container_name: status_maxatslega_github_profile
    restart: always